const express = require("express");
const router = express.Router();
const campusCart = require("../controller/campusCartController");
router.post("/send" , campusCart.sendText);
router.post("/receive" , campusCart.receiveText);
router.post("/login", campusCart.login);
router.post("/register", campusCart.register);
router.post("/", campusCart.token);
router.delete("/", campusCart.delToken);
router.post("/profile", campusCart.profile);
router.post("/deleteAccount", campusCart.delAcc);
router.post("/logout", campusCart.logout);
router.post("/allprod", campusCart.displayProd);
router.post("/sell", campusCart.sell);
router.post("/update", campusCart.update);
router.post("/prodData", campusCart.prodData);
router.post("/searchproduct", campusCart.searchproduct);
router.post("/fixdeal", campusCart.fixdeal);
router.post("/confirmdeal", campusCart.confirmdeal);
router.post("/deletemyprod", campusCart.deletemyprod);
router.post("/messages" , campusCart.msg);
router.post("/sendMessage", campusCart.getAllChats);
router.post("/verifyToken",campusCart.verifyingToken);
module.exports = router;